apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-realtime-dashboard
  labels:
    app: app1-realtime-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-realtime-dashboard
  template:
    metadata:
      labels:
        app: app1-realtime-dashboard
    spec:
      containers:
        - name: app1
          image: registry.gitlab.com/REPLACE_ORG/s25504_kafka/app1-realtime-dashboard:latest
          ports:
            - containerPort: 8080
          env:
            - name: ADD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: stock-api-key
                  key: ADD_API_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
